defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "ajn"

theme: jekyll-leap-day
title: The Nichol Family
description: Aidan & Margaret's Work
